_src/12/BrewHow/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web.Mvc;
using BrewHow.Domain.Entities;
using BrewHow.Domain.Repositories;
using BrewHow.Models;
using BrewHow.ViewModels;
using BrewHow.ViewModels.Mappers;
using WebMatrix.WebData;

namespace BrewHow.Controllers
{
    public class RecipeController : Controller
    {
        // Create references to the repositories used 
        // to retrieve and persist entities used by 
        // the recipe controller.
        private readonly IRecipeRepository _recipeRepository;
        private readonly IStyleRepository _styleRepository;
        private readonly IUserProfileEntityFactory _userProfileEntityFactory;
        private readonly IRecipeDisplayViewModelMapper _displayViewModelMapper;
        private readonly IRecipeEditViewModelMapper _editViewModelMapper;

        public RecipeController(IRecipeRepository recipeRepository,
            IStyleRepository styleRepository,
            IUserProfileEntityFactory userProfileEntityFactory,
            IRecipeDisplayViewModelMapper displayViewModelMapper,
            IRecipeEditViewModelMapper editViewModelMapper)
            : base()
        {
            this._recipeRepository = recipeRepository;
            this._styleRepository = styleRepository;
            this._userProfileEntityFactory = userProfileEntityFactory;
            this._displayViewModelMapper = displayViewModelMapper;
            this._editViewModelMapper = editViewModelMapper;
        }

        // Respond to requests to ~/ with the list of
        // recipes in the system.
        public async Task<ActionResult> Index(int page = 0)
        {
            var recipeListTask = Task.Factory.StartNew(() =>
            {
                var recipes = _recipeRepository.GetRecipes();

                var viewModel = new PagedResult<RecipeEntity, RecipeDisplayViewModel>(
                    recipes,
                    page,
                    this._displayViewModelMapper.EntityToViewModel);

                return viewModel;
            });

            return View(await recipeListTask);
        }

        // Retrieve all of the recipes of a certain style.
        public async Task<ActionResult> Style(string style, int page = 0)
        {
            var recipeListTask = Task.Factory.StartNew(() =>
            {
                var recipesForStyle =
                    _recipeRepository.GetRecipesByStyleSlug(style);

                var viewModel = new PagedResult<RecipeEntity, RecipeDisplayViewModel>(
                    recipesForStyle,
                    page,
                    this._displayViewModelMapper.EntityToViewModel);

                return viewModel;
            });

            var styleEntity = _styleRepository.GetStyleBySlug(style);

            if (style != null)
            {
                ViewBag.Title = styleEntity.Name + " Recipes";
            }

            return View("Index", await recipeListTask);
        }

        // Retrieve the details of a recipe from the
        // recipe repository and send them on to the 
        // view used to display them to the user.
        public ActionResult Details(int id)
        {
            var recipe =
                this._recipeRepository.GetRecipe(id);

            var viewModel =
                this._displayViewModelMapper.EntityToViewModel(recipe);

            return View(viewModel);
        }

        // Return a view that allows the requestor
        // to create new recipes.
        [Authorize]
        public ActionResult Create()
        {
            var viewModel = this
                ._editViewModelMapper
                .EntityToViewModel(null);

            return View(viewModel);
        }

        // Respond to the request to create a new 
        // recipe and return to the requestor the 
        // list of recipes if it's successful or
        // return them to the edit page on
        // failure.  ONLY respond to HTTP POST
        // requests.  The runtime will use model
        // binding to populate the recipe parameter.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecipeEditViewModel recipe)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var recipeEntity =
                        this._editViewModelMapper.ViewModelToEntity(recipe);

                    this._recipeRepository.Save(recipeEntity);

                    var context = Microsoft.AspNet.SignalR.
                        GlobalHost
                            .ConnectionManager
                            .GetHubContext<RecipeHub>();
                    context
                        .Clients
                        .All
                        .recipeAdded(
                            _displayViewModelMapper
                                .EntityToViewModel(recipeEntity)
                        );

                    return RedirectToAction("Index");
                }
            }
            catch
            {
            }

            return View(recipe);
        }

        // Return a view that allows the requestor
        // to edit a specific recipe.  Return to the
        // view a ViewModel representing the recipe.
        [Authorize]
        public ActionResult Edit(int id)
        {
            var recipeToEdit = 
                this
                ._recipeRepository
                .GetRecipe(id);

            if (!CanEdit(recipeToEdit))
            {
                // Simply return the user to the detail view.
                // Not too worried about the throw.
                return RedirectToAction("Details", 
                    new 
                    { 
                        id = id 
                    });
            }

            var viewModel = this
                ._editViewModelMapper
                .EntityToViewModel(recipeToEdit);

            return View(viewModel);
        }

        // Respond to the request to edit an
        // existing recipe and return to the 
        // requestor the list of recipes if it's
        // successful or return them to the edit 
        // page on failure.  ONLY respond to HTTP 
        // POST requests.  The runtime will use 
        // model binding to populate the recipe 
        // parameter.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RecipeEditViewModel recipe)
        {
            try
            {
                // Yes, it's a bit chatty, but we need to 
                // validate the entity from the database.
                var recipeEntity =
                    this._recipeRepository.GetRecipe(recipe.RecipeId);

                if (!CanEdit(recipeEntity))
                {
                    // Simply return the user to the detail view.
                    // Not too worried about the throw.
                    return RedirectToAction("Details", new { id = recipe.RecipeId });
                }

                var entityToSave = this
                    ._editViewModelMapper
                    .ViewModelToEntity(recipe);

                this._recipeRepository.Save(entityToSave);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private bool CanEdit(RecipeEntity entity)
        {
            if (Request.IsAuthenticated)
            {
                return WebSecurity.CurrentUserId == entity.Contributor.UserId;
            }

            return false;
        }
    }
}

_src/12/BrewHow/Controllers/StyleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BrewHow.Domain.Entities;
using BrewHow.Domain.Repositories;
using BrewHow.ViewModels;
using BrewHow.Models;
using System.Threading.Tasks;

namespace BrewHow.Controllers
{
    public class StyleController : Controller
    {
        private readonly IStyleRepository _styleRepository;

        public StyleController(IStyleRepository styleRepository)
        {
            this._styleRepository = styleRepository;
        }

        public async Task<ActionResult> Index(int page = 0)
        {
            var styleList = Task.Factory.StartNew(() =>
            {
                var viewModel = new PagedResult<StyleEntity, StyleDisplayViewModel>(
                    _styleRepository.GetStyles(),
                    page,
                    ToDisplayModel);

                return viewModel;
            });

            return View(await styleList);
        }

        /// <summary>
        /// Converts a recipe entity into the display model sent
        /// to the view.
        /// </summary>
        /// <param name="entity">The entity to convert</param>
        /// <returns>A RecipeDisplayViewModel that represents the underlying domain entity</returns>
        private StyleDisplayViewModel ToDisplayModel(StyleEntity entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(
                    "entity",
                    "Cannot convert an entity to a view model when no entity is passed.");
            }

            return new StyleDisplayViewModel
            {
                StyleId = entity.StyleId,
                Name = entity.Name,
                Slug = entity.Slug,
                Category = entity.Category.ToString()
            };
        }

    }
}

_src/12/BrewHow/Views/Shared/PagingPartial.cshtml
@model BrewHow.ViewModels.IPagedResult

<div id="pager">

@if (Model.Page > 0)
{
    @Html.RouteLink("<< Prev", new
    { 
        page = Model.Page - 1,
        controller = ViewContext.RouteData.Values["controller"],
        action = ViewContext.RouteData.Values["action"]
    },
    new
    {
        id = "paging-prev"
    });
}
<span>Page @(Model.Page + 1) of @Model.TotalPages</span>
@if (Model.Page + 1 != Model.TotalPages)
{
    @Html.RouteLink("Next >>", new
    {
        page = Model.Page + 1,
        controller = ViewContext.RouteData.Values["controller"],
        action = ViewContext.RouteData.Values["action"]
    },
    new
    {
        id = "paging-next"
    });
}
</div>

_src/12/BrewHow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - BrewHow</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("BrewHow", "Index", "Recipe", new { area = "" }, null)</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Recipes", "Index", "Recipe", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Styles", "Index", "Style", new { area = "" }, null)</li>
                            @if (Request.IsAuthenticated) {
                            <li>@Html.ActionLink("Library", "Index", "Library", new { area = "" }, null)</li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - BrewHow and ASP.NET MVC 4 Mobile App Development</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        <script src="~/Scripts/jquery.signalR-1.1.2.min.js" type="text/javascript"></script>
        <script src="~/signalr/hubs" type="text/javascript"></script>

        @RenderSection("scripts", required: false)
    </body>
</html>